# Generated by Django 5.2.7 on 2025-10-31 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.ocorrencia')),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='policial_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policial'),
        ),
        migrations.CreateModel(
            name='Suspeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('status', models.CharField(choices=[('Preso', 'Preso'), ('Foragido', 'Foragido')], default='Foragido', max_length=20)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspeitos', to='core.ocorrencia')),
            ],
        ),
        migrations.CreateModel(
            name='Vitima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('contato', models.CharField(max_length=20)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitimas', to='core.ocorrencia')),
            ],
        ),
    ]
