# Generated by Django 5.2.7 on 2025-11-03 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspeito',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='suspeito',
            name='ocorrencia',
        ),
        migrations.RemoveField(
            model_name='suspeito',
            name='status',
        ),
    ]
